//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Action_Boolean p_chalk_InteractUI;
        
        private static SteamVR_Action_Boolean p_chalk_Teleport;
        
        private static SteamVR_Action_Boolean p_chalk_GrabPinch;
        
        private static SteamVR_Action_Boolean p_chalk_GrabGrip;
        
        private static SteamVR_Action_Pose p_chalk_Pose;
        
        private static SteamVR_Action_Skeleton p_chalk_SkeletonLeftHand;
        
        private static SteamVR_Action_Skeleton p_chalk_SkeletonRightHand;
        
        private static SteamVR_Action_Single p_chalk_Squeeze;
        
        private static SteamVR_Action_Boolean p_chalk_HeadsetOnHead;
        
        private static SteamVR_Action_Boolean p_chalk_GrabPinchLeft;
        
        private static SteamVR_Action_Pose p_chalk_newPose;
        
        private static SteamVR_Action_Vibration p_chalk_Haptic;
        
        private static SteamVR_Action_Vector2 p_platformer_Move;
        
        private static SteamVR_Action_Boolean p_platformer_Jump;
        
        private static SteamVR_Action_Vector2 p_buggy_Steering;
        
        private static SteamVR_Action_Single p_buggy_Throttle;
        
        private static SteamVR_Action_Boolean p_buggy_Brake;
        
        private static SteamVR_Action_Boolean p_buggy_Reset;
        
        private static SteamVR_Action_Pose p_mixedreality_ExternalCamera;
        
        public static SteamVR_Action_Boolean chalk_InteractUI
        {
            get
            {
                return SteamVR_Actions.p_chalk_InteractUI.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean chalk_Teleport
        {
            get
            {
                return SteamVR_Actions.p_chalk_Teleport.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean chalk_GrabPinch
        {
            get
            {
                return SteamVR_Actions.p_chalk_GrabPinch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean chalk_GrabGrip
        {
            get
            {
                return SteamVR_Actions.p_chalk_GrabGrip.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Pose chalk_Pose
        {
            get
            {
                return SteamVR_Actions.p_chalk_Pose.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Skeleton chalk_SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.p_chalk_SkeletonLeftHand.GetCopy<SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Skeleton chalk_SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.p_chalk_SkeletonRightHand.GetCopy<SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Single chalk_Squeeze
        {
            get
            {
                return SteamVR_Actions.p_chalk_Squeeze.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Boolean chalk_HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.p_chalk_HeadsetOnHead.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean chalk_GrabPinchLeft
        {
            get
            {
                return SteamVR_Actions.p_chalk_GrabPinchLeft.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Pose chalk_newPose
        {
            get
            {
                return SteamVR_Actions.p_chalk_newPose.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Vibration chalk_Haptic
        {
            get
            {
                return SteamVR_Actions.p_chalk_Haptic.GetCopy<SteamVR_Action_Vibration>();
            }
        }
        
        public static SteamVR_Action_Vector2 platformer_Move
        {
            get
            {
                return SteamVR_Actions.p_platformer_Move.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Boolean platformer_Jump
        {
            get
            {
                return SteamVR_Actions.p_platformer_Jump.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vector2 buggy_Steering
        {
            get
            {
                return SteamVR_Actions.p_buggy_Steering.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Single buggy_Throttle
        {
            get
            {
                return SteamVR_Actions.p_buggy_Throttle.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Boolean buggy_Brake
        {
            get
            {
                return SteamVR_Actions.p_buggy_Brake.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean buggy_Reset
        {
            get
            {
                return SteamVR_Actions.p_buggy_Reset.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Pose mixedreality_ExternalCamera
        {
            get
            {
                return SteamVR_Actions.p_mixedreality_ExternalCamera.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        private static void InitializeActionArrays()
        {
            Valve.VR.SteamVR_Input.actions = new Valve.VR.SteamVR_Action[] {
                    SteamVR_Actions.chalk_InteractUI,
                    SteamVR_Actions.chalk_Teleport,
                    SteamVR_Actions.chalk_GrabPinch,
                    SteamVR_Actions.chalk_GrabGrip,
                    SteamVR_Actions.chalk_Pose,
                    SteamVR_Actions.chalk_SkeletonLeftHand,
                    SteamVR_Actions.chalk_SkeletonRightHand,
                    SteamVR_Actions.chalk_Squeeze,
                    SteamVR_Actions.chalk_HeadsetOnHead,
                    SteamVR_Actions.chalk_GrabPinchLeft,
                    SteamVR_Actions.chalk_newPose,
                    SteamVR_Actions.chalk_Haptic,
                    SteamVR_Actions.platformer_Move,
                    SteamVR_Actions.platformer_Jump,
                    SteamVR_Actions.buggy_Steering,
                    SteamVR_Actions.buggy_Throttle,
                    SteamVR_Actions.buggy_Brake,
                    SteamVR_Actions.buggy_Reset,
                    SteamVR_Actions.mixedreality_ExternalCamera};
            Valve.VR.SteamVR_Input.actionsIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.chalk_InteractUI,
                    SteamVR_Actions.chalk_Teleport,
                    SteamVR_Actions.chalk_GrabPinch,
                    SteamVR_Actions.chalk_GrabGrip,
                    SteamVR_Actions.chalk_Pose,
                    SteamVR_Actions.chalk_SkeletonLeftHand,
                    SteamVR_Actions.chalk_SkeletonRightHand,
                    SteamVR_Actions.chalk_Squeeze,
                    SteamVR_Actions.chalk_HeadsetOnHead,
                    SteamVR_Actions.chalk_GrabPinchLeft,
                    SteamVR_Actions.chalk_newPose,
                    SteamVR_Actions.platformer_Move,
                    SteamVR_Actions.platformer_Jump,
                    SteamVR_Actions.buggy_Steering,
                    SteamVR_Actions.buggy_Throttle,
                    SteamVR_Actions.buggy_Brake,
                    SteamVR_Actions.buggy_Reset,
                    SteamVR_Actions.mixedreality_ExternalCamera};
            Valve.VR.SteamVR_Input.actionsOut = new Valve.VR.ISteamVR_Action_Out[] {
                    SteamVR_Actions.chalk_Haptic};
            Valve.VR.SteamVR_Input.actionsVibration = new Valve.VR.SteamVR_Action_Vibration[] {
                    SteamVR_Actions.chalk_Haptic};
            Valve.VR.SteamVR_Input.actionsPose = new Valve.VR.SteamVR_Action_Pose[] {
                    SteamVR_Actions.chalk_Pose,
                    SteamVR_Actions.chalk_newPose,
                    SteamVR_Actions.mixedreality_ExternalCamera};
            Valve.VR.SteamVR_Input.actionsBoolean = new Valve.VR.SteamVR_Action_Boolean[] {
                    SteamVR_Actions.chalk_InteractUI,
                    SteamVR_Actions.chalk_Teleport,
                    SteamVR_Actions.chalk_GrabPinch,
                    SteamVR_Actions.chalk_GrabGrip,
                    SteamVR_Actions.chalk_HeadsetOnHead,
                    SteamVR_Actions.chalk_GrabPinchLeft,
                    SteamVR_Actions.platformer_Jump,
                    SteamVR_Actions.buggy_Brake,
                    SteamVR_Actions.buggy_Reset};
            Valve.VR.SteamVR_Input.actionsSingle = new Valve.VR.SteamVR_Action_Single[] {
                    SteamVR_Actions.chalk_Squeeze,
                    SteamVR_Actions.buggy_Throttle};
            Valve.VR.SteamVR_Input.actionsVector2 = new Valve.VR.SteamVR_Action_Vector2[] {
                    SteamVR_Actions.platformer_Move,
                    SteamVR_Actions.buggy_Steering};
            Valve.VR.SteamVR_Input.actionsVector3 = new Valve.VR.SteamVR_Action_Vector3[0];
            Valve.VR.SteamVR_Input.actionsSkeleton = new Valve.VR.SteamVR_Action_Skeleton[] {
                    SteamVR_Actions.chalk_SkeletonLeftHand,
                    SteamVR_Actions.chalk_SkeletonRightHand};
            Valve.VR.SteamVR_Input.actionsNonPoseNonSkeletonIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.chalk_InteractUI,
                    SteamVR_Actions.chalk_Teleport,
                    SteamVR_Actions.chalk_GrabPinch,
                    SteamVR_Actions.chalk_GrabGrip,
                    SteamVR_Actions.chalk_Squeeze,
                    SteamVR_Actions.chalk_HeadsetOnHead,
                    SteamVR_Actions.chalk_GrabPinchLeft,
                    SteamVR_Actions.platformer_Move,
                    SteamVR_Actions.platformer_Jump,
                    SteamVR_Actions.buggy_Steering,
                    SteamVR_Actions.buggy_Throttle,
                    SteamVR_Actions.buggy_Brake,
                    SteamVR_Actions.buggy_Reset};
        }
        
        private static void PreInitActions()
        {
            SteamVR_Actions.p_chalk_InteractUI = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Chalk/in/InteractUI")));
            SteamVR_Actions.p_chalk_Teleport = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Chalk/in/Teleport")));
            SteamVR_Actions.p_chalk_GrabPinch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Chalk/in/GrabPinch")));
            SteamVR_Actions.p_chalk_GrabGrip = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Chalk/in/GrabGrip")));
            SteamVR_Actions.p_chalk_Pose = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/Chalk/in/Pose")));
            SteamVR_Actions.p_chalk_SkeletonLeftHand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create<SteamVR_Action_Skeleton>("/actions/Chalk/in/SkeletonLeftHand")));
            SteamVR_Actions.p_chalk_SkeletonRightHand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create<SteamVR_Action_Skeleton>("/actions/Chalk/in/SkeletonRightHand")));
            SteamVR_Actions.p_chalk_Squeeze = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/Chalk/in/Squeeze")));
            SteamVR_Actions.p_chalk_HeadsetOnHead = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Chalk/in/HeadsetOnHead")));
            SteamVR_Actions.p_chalk_GrabPinchLeft = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Chalk/in/GrabPinchLeft")));
            SteamVR_Actions.p_chalk_newPose = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/Chalk/in/newPose")));
            SteamVR_Actions.p_chalk_Haptic = ((SteamVR_Action_Vibration)(SteamVR_Action.Create<SteamVR_Action_Vibration>("/actions/Chalk/out/Haptic")));
            SteamVR_Actions.p_platformer_Move = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/platformer/in/Move")));
            SteamVR_Actions.p_platformer_Jump = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/platformer/in/Jump")));
            SteamVR_Actions.p_buggy_Steering = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/buggy/in/Steering")));
            SteamVR_Actions.p_buggy_Throttle = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/buggy/in/Throttle")));
            SteamVR_Actions.p_buggy_Brake = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/buggy/in/Brake")));
            SteamVR_Actions.p_buggy_Reset = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/buggy/in/Reset")));
            SteamVR_Actions.p_mixedreality_ExternalCamera = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/mixedreality/in/ExternalCamera")));
        }
    }
}
